//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tax_Table
    {
        public int Id { get; set; }
        public string PAN { get; set; }
        public string DOB { get; set; }
        public string Mobile { get; set; }
        public string Address { get; set; }
        public string EmailID { get; set; }
        public string FathersName { get; set; }
        public string City { get; set; }
        public string VAT { get; set; }
    }
}
